version: '3'

networks:
  default:
    external:
      name: quic_test_net

services:
  node-quic-example:
    container_name: node-quic-example
    image: myeongkil/node-quic:latest
    working_dir: /usr/app
    environment:
      - PORT=1234
    volumes:
        - ./build:/usr/app
    command: node quic-server.js